### PR TITLE
Allow edge-proxy to forward container domain traffic

### PR DESCRIPTION
**Pull request by ashishwigwag**
1. Modify edge-proxy launch script to add new forwarding address for containers domain
2. Add `containers.local` to the list of known hosts
3. Update pe-utils

### CODE REVIEW

**Comment by costanic** [comment]
Rebased on dev.  @ashishwigwag Please make sure the rebase still looks good and that this PR is still required.

**Review by costanic — APPROVED** [review]

**Comment by ashishwigwag** [comment]
@costanic Could you see why some checks are failing?

**Comment by costanic** [comment]
> @costanic Could you see why some checks are failing?

Looks like some cloud-side issue.  According to the local edge-core process, the gateway is registered and has a device-id, but the cloud says the device-id doesn't exist.  I restarted the tests.

```
[2021-06-14T11:08:46.052Z] [2021-06-14T11:08:46.052Z] 11:08:45.773   INFO     stdout: {"account-id":"0177aa7fa2d79a163bfb0dee00000000","edge-version":"unknown-release-branchless-uncommited-uninited","endpoint-name":"017a0a3543380000000000010013704f","internal-id":"017a0a3543380000000000010013704f","lwm2m-server-uri":"coaps://tcp-lwm2m.us-east-1.mbedcloud.com:5684?aid=0177aa7fa2d79a163bfb0dee00000000&iep=017a0a3543380000000000010013704f","status":"connected"}
```

and later...

```
[2021-06-14T11:10:28.789Z] [2021-06-14T11:10:28.789Z] 11:10:28.555   INFO     Executing local command: curl -X GET -v   https://edge-k8s.us-east-1.mbedcloud.com/api/v1/nodes/017a0a3543380000000000010013704f  -H 'Authorization: Bearer ak_2MDE3N2FhN2ZhMmQ3OWExNjNiZmIwZGVlMDAwMDAwMDA0177b38f38919a163bfb0dee00000000pO0YffD1X3Cb7EuehHrAQfUfJxEtJteu'
[2021-06-14T11:10:29.045Z] [2021-06-14T11:10:29.045Z] 11:10:28.858   INFO     stdout {
[2021-06-14T11:10:29.045Z] [2021-06-14T11:10:29.045Z]   "kind": "Status",
[2021-06-14T11:10:29.045Z] [2021-06-14T11:10:29.045Z]   "apiVersion": "v1",
[2021-06-14T11:10:29.045Z] [2021-06-14T11:10:29.045Z]   "metadata": {
[2021-06-14T11:10:29.045Z] [2021-06-14T11:10:29.045Z]     
[2021-06-14T11:10:29.045Z] [2021-06-14T11:10:29.045Z]   },
[2021-06-14T11:10:29.045Z] [2021-06-14T11:10:29.045Z]   "status": "Failure",
[2021-06-14T11:10:29.045Z] [2021-06-14T11:10:29.045Z]   "message": "nodes \"017a0a3543380000000000010013704f\" not found",
[2021-06-14T11:10:29.045Z] [2021-06-14T11:10:29.045Z]   "reason": "NotFound",
[2021-06-14T11:10:29.045Z] [2021-06-14T11:10:29.045Z]   "details": {
[2021-06-14T11:10:29.045Z] [2021-06-14T11:10:29.045Z]     "name": "017a0a3543380000000000010013704f",
[2021-06-14T11:10:29.045Z] [2021-06-14T11:10:29.045Z]     "kind": "nodes"
[2021-06-14T11:10:29.045Z] [2021-06-14T11:10:29.045Z]   },
[2021-06-14T11:10:29.045Z] [2021-06-14T11:10:29.045Z]   "code": 404
[2021-06-14T11:10:29.045Z] [2021-06-14T11:10:29.045Z] }
```

**Comment by costanic** [comment]
rebased on dev to kick the CI tests again

**Comment by ashishwigwag** [comment]
@costanic can we merge this?

**Comment by costanic** [comment]
> @costanic can we merge this?

Can't merge until CI passes.  I'll kick the tests again, hopefully they have been fixed.

**Comment by costanic** [comment]
@ashishwigwag This commit is still failing CI, but [CI itself seems to be ok right now](https://github.com/PelionIoT/distro-pelion-edge/pull/175).  Have you tried your change locally to make sure it works?

**Comment by ashishwigwag** [comment]
@costanic I can't think of anything else.
pe-utils is already updated to 2.0.7 so identity tool is updated.

- `containers.local` is being added here to /etc/hosts
- edge-proxy has one more forwarding address

That is pretty much what we also did in snap and meta
https://github.com/PelionIoT/snap-pelion-edge/pull/379/files
https://github.com/PelionIoT/meta-pelion-edge/pull/309/files

**Comment by ygoyal18** [comment]
@ashishwigwag Have you verified this change in your local setup?

**Comment by ashishwigwag** [comment]
> @ashishwigwag Have you verified this change in your local setup?

Was able to build it today, there was a bash cmd issue, corrected.

**Comment by costanic** [comment]
rebased on dev again due to this fix: https://github.com/PelionIoT/distro-pelion-edge/pull/189

**Comment by ashishwigwag** [comment]
I guess we can merge this now @costanic .

**Pull request merged**
