### PR TITLE
byoc version of edge-core

### PR DESCRIPTION
**Pull request by costanic**
BYOC version of edge-core differs from the other variants of edge-core
in the way that it is provisioned.  byoc mode takes a CBOR file as input
during the initial provisioning process, whereas devmode is compiled with
credentials and factory-mode receives credentials during a factory
provisioning process using FCC.

The CBOR file can be generated from developer credentials downloaded
from the Pelion Portal (the same credentials "C" files used to compile
into devmode edge-core) by a tool called edge-tool [1], or it can be
generated by FCCE [2].

[1] https://github.com/PelionIoT/mbed-edge/tree/master/edge-tool
[2] https://github.com/PelionIoT/factory-configurator-client-example

### CODE REVIEW

**Comment by costanic** [comment]
haven't dev-tested yet, not ready for merge.

**Comment by costanic** [comment]
This passed dev-test so I removed the do-not-merge label.  This is ready for review.

**Review by mray190 — APPROVED** [review]
LGTM.
Lot of code but pretty straightforward

**Review by johnmichaelwelsh — APPROVED** [review]
Lotsa patches that I am already familiar with. Looks good.

**Pull request merged**
