### PR TITLE
Fix packages verification

### PR DESCRIPTION
**Pull request by kbgl**
Use correct docker image for packages verification (*-source instead of *-build) - that image has lintian installed during image creation.

### CODE REVIEW

**Review by ryannowarm — CHANGES_REQUESTED** [review]
>Use correct docker image for packages verification (*-source instead of *-build) - that image has lintian installed during image creation.

Please put this in the actual commit description.

**Comment by sameer2209-arm** [comment]
@kbgl only rhel build is successful. Rest all the builds are failing with the following error:
`W: golang-virtual: new-package-should-close-itp-bug

N: 

N:    This package appears to be the first packaging of a new upstream

N:    software package (there is only one changelog entry and the Debian

N:    revision is 1), but it does not close any bugs. The initial upload of a

N:    new package should close the corresponding ITP bug for that package.

N:    

N:    This warning can be ignored if the package is not intended for Debian or

N:    if it is a split of an existing Debian package.

N:    

N:    Refer to Debian Developer's Reference section 5.1 (New packages) for

N:    details.

N:    

N:    Severity: normal, Certainty: certain

N:    

N:    Check: changelog-file, Type: binary

N: 

E: golang-virtual: extended-description-is-empty

N: 

N:    The extended description (the lines after the first line of the

N:    "Description:" field) is empty.

N:    

N:    Refer to Debian Policy Manual section 3.4 (The description of a package)

N:    for details.

N:    

N:    Severity: serious, Certainty: certain

N:    

N:    Check: description, Type: binary, udeb

N: 

script returned exit code 1`

**Comment by sameer2209-arm** [comment]
@kbgl This PR is failing bionic arm64 build because the current dev branch has the broken build for bionic arm64 as this PR #181 was merged even though PR checks did not pass for it. I have already created the defect Jira ticket for it.  
Since all the other build combinations are successfully passing for your PR, I would say it is safe to assume that it will work for bionic arm64 too.

**Comment by ryannowarm** [comment]
FYI, the bionic arm64 fluentbit build [has been fixed](https://github.com/PelionIoT/distro-pelion-edge/pull/189)

**Review by sameer2209-arm — APPROVED** [review]
All PR checks successfully passing.

**Review by ryannowarm — APPROVED** [review]

**Comment by ryannowarm** [comment]
Rebased to run recently added github actions builds here: https://github.com/PelionIoT/distro-pelion-edge/pull/192

**Pull request merged**
