### PR TITLE
Fix FCC Ethernet support

### PR DESCRIPTION
**Pull request by kbgl**
This change bumps fcc to 4.8.0 and adds support for changing TCP port and Ethernet interface in configuration (`/etc/default/mbed-fcc` is not created by default - does not change current behavior;  `mbed-fcc.example` file provided). Configuration can be a part of factory scripts package installed separately (customized for each manufacturer).

### CODE REVIEW

**Review by costanic — CHANGES_REQUESTED** [review]
Why are we removing CBOR support?

**Comment by kbgl** [comment]
> Why are we removing CBOR support?

The patch was not applying anymore on newer version. On older fcc the change was causing segfaults if `device.cbor` file was missing (missing error checks). I'm not sure what was the use case for this, but with the patch it was not possible to provision the device over TCP. We can try to re-implement support for `device.cbor` but I need to know how it is used.

**Comment by costanic** [comment]
> > Why are we removing CBOR support?
> 
> The patch was not applying anymore on newer version. On older fcc the change was causing segfaults if `device.cbor` file was missing (missing error checks). I'm not sure what was the use case for this, but with the patch it was not possible to provision the device over TCP. We can try to re-implement support for `device.cbor` but I need to know how it is used.

ok yeah, CBOR support is a current customer requirement, and [this line](https://github.com/PelionIoT/distro-pelion-edge/blob/988a7454f8f5170abf9182d9ff685a1df8464379/mbed-fcc/deb/debian/launch-fcc.sh#L28) in the startup script should have prevented mbed-fcc from starting if the device.cbor file was missing.

We'll need to find some way for these two modes to coexist.

**Review by ryannowarm — CHANGES_REQUESTED** [review]
Yup, need to have CBOR support

**Comment by costanic** [comment]
@kbgl mbed-fcc latest is [4.9.0.](https://github.com/PelionIoT/factory-configurator-client-example/releases/tag/4.9.0)

**Comment by costanic** [comment]
> @kbgl mbed-fcc latest is [4.9.0.](https://github.com/PelionIoT/factory-configurator-client-example/releases/tag/4.9.0)

Also, CBOR the patch still applies cleanly to 4.9.0.

**Comment by kbgl** [comment]
> > @kbgl mbed-fcc latest is [4.9.0.](https://github.com/PelionIoT/factory-configurator-client-example/releases/tag/4.9.0)
> 
> Also, CBOR the patch still applies cleanly to 4.9.0.

Compiled fine for ARM64, now I am testing it

**Comment by kbgl** [comment]
> > > @kbgl mbed-fcc latest is [4.9.0.](https://github.com/PelionIoT/factory-configurator-client-example/releases/tag/4.9.0)
> > 
> > 
> > Also, CBOR the patch still applies cleanly to 4.9.0.
> 
> Compiled fine for ARM64, now I am testing it

4.9.0 tested OK - for me it works same as 4.8.0.

**Review by costanic — APPROVED** [review]

**Review by ryannowarm — APPROVED** [review]

**Pull request merged**
