### PR TITLE
Upgraded edge-core and examples to latest and removed the customer feature patches

### PR DESCRIPTION
**Pull request by whygoyal**
This is for developers to build a VM with latest edge-core software who do not need customer specific features.

### CODE REVIEW

**Comment by costanic** [comment]
Thanks for the PR.  I think the question we need to ask ourselves now is whether we should be upgrading edge-core piecemeal like this and leaving all the other Pelion Edge packages behind.  We have this notion of a single Pelion Edge version that can be used as a reference across the various builds (snap-pelion-edge, meta-pelion-edge, etc.), for example Pelion Edge 2.2 and Pelion Edge 2.3, and right now it looks like distro-pelion-edge is only up to date with 2.1.  Further, edge-core 0.17.0 is not included in any official Pelion Edge version yet.

**Comment by ygoyal18** [comment]
Because we don't have bandwidth to upgrade all the pieces at once, we are bring it as needed. If we are recommending developers to use VM as we do not have dev version of Yocto builds which have debug tools and compilers installed, then VM needs to stay ahead of the other distros.

**Comment by costanic** [comment]
> Because we don't have bandwidth to upgrade all the pieces at once, we are bring it as needed. If we are recommending developers to use VM as we do not have dev version of Yocto builds which have debug tools and compilers installed, then VM needs to stay ahead of the other distros.

OK, that's an interesting idea.  I thought we were using Yocto for that, but if Yocto doesn't have build tools and stuff, then you're right it makes sense to use the debian packages, and in fact our team has done this in the past when working on some edge-proxy features.  But that kinda changes how we think about distro-pelion-edge, because previously we just updated it when needed because the meta layer in Yocto was the source of truth for Pelion Edge versioning.  I'm all for it, we just need to discuss this internally a little more.

**Comment by mray190** [comment]
Rolled into the 2.4 upgrade. See other PRs

**Pull request closed without merging**
